name: Release

on:
  push:
    # On Tag / Release by Mask
    tags:
      - "v*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.current_release.outputs.name }}
      version: ${{ steps.current_release.outputs.tag_name }}
      url: ${{ steps.current_release.outputs.html_url }}
    steps:
      - name: ğŸ‘€ Get Current Release
        id: current_release
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build / PixelClock
    needs:
      - prepare
    uses: ./.github/workflows/build.yaml
    with:
      release-summary: ${{ needs.prepare.outputs.name }}
      release-url: ${{ needs.prepare.outputs.url }}

  release:
    name: Release
    needs:
      - build
    permissions:
      contents: write
      discussions: write

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Download PixelClock Artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: PixelClock-*
          path: release-pixel-clock-files
          merge-multiple: true

      - name: ğŸ‘€ Check PixelClock artifacts
        run: |
          ls -l
        working-directory: release-pixel-clock-files

      - name: ğŸ­ Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-pixel-clock-files/*.factory.bin
          discussion_category_name: Announcements

  cleanup:
    name: GitHub Pages / Delete deployment
    runs-on: ubuntu-latest
    permissions: write-all
    needs:
      - build

    steps:
      - name: ğŸ§¹ Delete deployment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pixel-clock
          onlyRemoveDeployments: true

  publish:
    name: Publish new firmware and website to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - cleanup

    environment:
      name: pixel-clock
      url: ${{ steps.deployment.outputs.page_url }}

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: â¬‡ï¸ Checkout website files
        uses: actions/checkout@v6

      - name: ğŸ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: ğŸ“¦ Install mkDocs
        run: pip install mkdocs-material

      - name: ğŸ’… Build the docs site
        run: mkdocs build --config-file .mkdocs.yml

      - name: ğŸ“¦ Download PixelClock Artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: PixelClock-*
          path: release-pixel-clock-files
          merge-multiple: true

      - name: ğŸ’… Copy PixelClock artifacts files
        run: |
          mkdir site/pixel-clock
          cp -R release-pixel-clock-files/* site/pixel-clock/

      - name: ğŸ’… Copy website files
        run: cp -R static/* site/

      - name: ğŸ‘€ Check output
        run: |
          ls -l
        working-directory: site/pixel-clock

      - name: ğŸ­ Setup Pages
        uses: actions/configure-pages@v5

      - name: ğŸš€ Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - name: ğŸ’… Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: ğŸ§¹ Delete Artifacts / Github Pages
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
          failOnError: false
